modLoader="javafml"
loaderVersion="[28,29)"
license="All Rights Reserved"

[[mods]]
modId="ped"
version="${file.jarVersion}"
displayName="ped"
authors="TheDoctorTTV"
description='''Player Experience Display.'''

[[dependencies.ped]]
modId="forge"
mandatory=true
versionRange="[28.2.26,29)"
ordering="NONE"
side="BOTH"

[[dependencies.ped]]
modId="minecraft"
mandatory=true
versionRange="[1.14.4]"
ordering="NONE"
side="BOTH"
